Create README.md
shrinkwrap/shrinkwrap pull request #149
Opened 2022-11-04 14:41 UTC by kabir

2022-11-07 15:13 UTC, bartoszmajsak requested changes
Thanks for putting this together. There are a few mistakes in markdown syntax. I added suggestions for ease of correcting it all at once.

2022-11-07 15:13 UTC, bartoszmajsak commented on README.md
> += Shrinkwrap
```suggestion
# Shrinkwrap
```

2022-11-07 15:13 UTC, bartoszmajsak commented on README.md
> +ShrinkWrap is a library to create archives from Java, which powers the [Arquillian]([url](https://github.com/arquillian))
```suggestion
ShrinkWrap is a library to create archives from Java, which powers the [Arquillian](https://github.com/arquillian)
```

2022-11-07 15:13 UTC, bartoszmajsak commented on README.md
> +Some information on how to use Shrinkwrap to create archives with Arquillian can be found in this [guide[(https://arquillian.org/guides/shrinkwrap_introduction/)
```suggestion
Some information on how to use Shrinkwrap to create archives with Arquillian can be found in this [guide](https://arquillian.org/guides/shrinkwrap_introduction/)
```

2022-11-07 15:34 UTC, kabir commented
@bartoszmajsak Thanks for the suggestions, I've incorporated them. This was all done in a bit of a rush as you can probably tell :-)

2022-11-08 08:55 UTC, bartoszmajsak approved these changes

2022-11-08 08:56 UTC, merged