[SHRINKWRAP-369] ShrinkWrapClassLoader find ServiceProviders in WAR
shrinkwrap/shrinkwrap pull request #49
Opened 2012-01-31 10:26 UTC by DavideD

Can this work?

The ShrinkwrapClassloader look for a specified path and if it cannot find the ndoe than look for the asset in WEB-INF/classes/

2022-02-06 21:13 UTC, DavideD commented
I'm surprised to see my PR re-opened. I've rebased it to the latest changes in main if it's something that can be helpful.
It's been 10 years, so I don't remember anything about it :)

2022-02-11 10:56 UTC, bartoszmajsak requested changes
Two minor suggestions. Thanks for taking care of the rebase!

2022-02-11 10:56 UTC, bartoszmajsak commented on api/src/main/java/org/jboss/shrinkwrap/api/classloader/ShrinkWrapClassLoader.java
> +                              return node;
```suggestion
                           if (node != null) {
                              return node;
                           }
```

2022-02-11 10:56 UTC, bartoszmajsak commented on api/src/main/java/org/jboss/shrinkwrap/api/classloader/ShrinkWrapClassLoader.java
> +                              return node;
```suggestion
                           if (node != null) {
                              return node;
                           }
```

2022-02-12 07:34 UTC, bartoszmajsak approved these changes
Thank you!

2022-02-12 07:35 UTC, merged